### ISSUE TITLE
there alots of issues while compiling zephir from converted code

### ISSUE THREAD

**Issue by surjit** [fezfez/php-to-zephir#33]
below log, when php to zephir

```
I have uploaded all code here [](https://github.com/surjit/zephir_ext)
```

please help me to sort the issues

Convert php to zephir

```
 81/81 [============================] 100% 4 secs/4 secs

+---------------+-----------------------------+------+-----------------+
| Incompatibility                                                      |
+---------------+-----------------------------+------+-----------------+
| Type          | Message                     | Line | Class           |
+---------------+-----------------------------+------+-----------------+
| ArrayFetchDim | supported funccall in array | 16   | CharCountBased  |
| ArrayFetchDim | supported funccall in array | 16   | CharCountBased  |
| ArrayFetchDim | supported funccall in array | 16   | GroupCountBased |
| ArrayFetchDim | supported funccall in array | 16   | GroupCountBased |
| ArrayFetchDim | supported funccall in array | 630  | Request         |
| ArrayFetchDim | supported funccall in array | 630  | Request         |
| ArrayFetchDim | supported funccall in array | 630  | Request         |
+---------------+-----------------------------+------+-----------------+

```

this one when I do zephir compile

```
Zephir\ParseException: Syntax error in /home/php-to-zephir/converted/Zesle/zesle/fastroute/dispatcher/charcountbased.zep on line 7

            var this->staticRouteMap, this->variableRouteData, tmpListThis->staticRouteMapThis->variableRouteData;
    -----------------^

at Library/CompilerFile.php(570)
#0 Library/Compiler.php(318): Zephir\CompilerFile->preCompile(Object(Zephir\Compiler))
#1 Library/Compiler.php(357): Zephir\Compiler->preCompile('zesle/fastroute...')
#2 Library/Compiler.php(904): Zephir\Compiler->recursivePreCompile('zesle')
#3 Library/Compiler.php(1131): Zephir\Compiler->generate(Object(Zephir\Commands\CommandBuild))
#4 Library/Compiler.php(1250): Zephir\Compiler->compile(Object(Zephir\Commands\CommandBuild), false)
#5 Library/Compiler.php(1331): Zephir\Compiler->install(Object(Zephir\Commands\CommandBuild), false)
#6 Library/Commands/CommandAbstract.php(108): Zephir\Compiler->build(Object(Zephir\Commands\CommandBuild))
#7 Library/Bootstrap.php(200): Zephir\Commands\CommandAbstract->execute(Object(Zephir\Config), Object(Zephir\Logger))
#8 compiler.php(21): Zephir\Bootstrap::boot()
#9 {main}
```

**Comment by fezfez** [comment]
Thanks for the report, i'll try to take a look this week-end.

**Comment by surjit** [comment]
thanks it will help, please suggest me simple routing framework that can be build as zephir ext (few files will work)
